### ISSUE TITLE
maven central repository?

### ISSUE THREAD

**Issue by bluej100** [pfgray/basiclti-util-java#3]
This seems to me like something that would be useful to have in the Maven central repository. Would there be an obstacle to that?

(Apologies if this is a dumb question. Java is not my native ecosystem.)

**Comment by pfgray** [comment]
Not a dumb question at all, that's actually been the plan all along!
Before I uploaded something to Maven central scoped under org.imsglobal, I wanted to contact someone from IMS to make sure our efforts are unified, but I don't think it's that big of a deal. I also figured it would be good to let the community use it for a bit, in order to work out any kinks.
The only obstacle is someone publishing the repo to Maven central: http://maven.apache.org/guides/mini/guide-central-repository-upload.html which is fairly easy to do.

**Comment by bluej100** [comment]
Oh, fantastic. Glad to hear it.
Sounds like this project would be a good candidate for the Sonatype OSS repository? I would be happy to do that busy work if you liked.

**Comment by pfgray** [comment]
I wouldn't be opposed to that at all. I just published a release on this repo with a compiled jar, so you can upload that jar file to the Sonatype OSS repository like you mentioned. Let me know if you need any help with that, thanks!

**Comment by bluej100** [comment]
Would you mind registering for an account on https://issues.sonatype.org/ and sending me your username? That way you'll be able to deploy in the future.

**Comment by bluej100** [comment]
We've been approved for release at https://issues.sonatype.org/browse/OSSRH-10587 . Should be synced up soon.

**Comment by bluej100** [comment]
The next step will be setting up an automatic Maven release profile ( http://central.sonatype.org/pages/apache-maven.html ).
